name: Container Build + Security Scan

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "25 22 * * 5"

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  container-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest

      - name: Generate SBOM
        uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d # v.0.23.1
        with:
          image: localbuild/testimage:latest
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Run Grype scan
        id: grype
        uses: anchore/scan-action@7037fa011853d5a11690026fb85feee79f4c946c # v7.3.2
        with:
          image: localbuild/testimage:latest
          severity-cutoff: high
          fail-build: false

      - name: Upload Grype SARIF
        uses: github/codeql-action/upload-sarif@0c0c5dc2f136b98cb0537075ccfa21f94cd9a63e # v2.24.3
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v.0.35.0
        with:
          image-ref: localbuild/testimage:latest
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sari@0c0c5dc2f136b98cb0537075ccfa21f94cd9a63e # v2.24.3
        with:
          sarif_file: trivy-results.sarif

      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v.4.1.0

      - name: Sign container (keyless)
        run: cosign sign --yes localbuild/testimage:latest
